package dockerfile

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

var chiselDockerfileTemplate = `# Generated by: chisel-dockerfile
# Original base: {{.OriginalBase}}

# Stage 1: Chisel — extract minimal filesystem
FROM alpine AS chisel-stage
ARG CHISEL_VERSION=1.1.0
ARG TARGETARCH
RUN wget -qO - "https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz" \
    | tar -xz --no-same-owner -C /usr/local/bin chisel
WORKDIR /rootfs
RUN chisel cut --release {{.Release}} --root /rootfs \
{{- range $i, $slice := .Slices}}
    {{$slice}}{{if not (last $i $.Slices)}} \{{end}}
{{- end}}

{{- if .HasBuildStage}}

# Stage 2: Application build (from original Dockerfile)
{{.BuildStageContent}}
{{- end}}

# Stage {{.FinalStageNum}}: Final chiseled image
FROM scratch
COPY --from=chisel-stage /rootfs /
{{- range .CopyInstructions}}
{{.}}
{{- end}}
{{- range .MetaInstructions}}
{{.}}
{{- end}}
`

// templateData holds the data for generating the output Dockerfile.
type templateData struct {
	OriginalBase      string
	Release           string
	Slices            []string
	HasBuildStage     bool
	BuildStageContent string
	FinalStageNum     int
	CopyInstructions  []string
	MetaInstructions  []string
}

// Generate produces an optimized multi-stage Dockerfile from the parsed
// info and resolved slices.
func Generate(info *DockerfileInfo, result *ResolveResult) ([]byte, error) {
	if info == nil || result == nil {
		return nil, fmt.Errorf("missing parsed info or resolve result")
	}

	data := templateData{
		Release:       result.Release,
		Slices:        result.Slices,
		FinalStageNum: 2,
	}

	// Find the Ubuntu runtime stage and any build stages.
	for _, stage := range info.Stages {
		if stage.IsUbuntu && stage.Alias == "" {
			// This is the runtime stage — extract metadata.
			data.OriginalBase = stage.BaseImage
			for _, inst := range stage.Lines {
				if inst.IsAptInstall {
					continue
				}
				switch inst.Directive {
				case "COPY":
					data.CopyInstructions = append(data.CopyInstructions, inst.Raw)
				case "ENV", "WORKDIR", "ENTRYPOINT", "CMD", "EXPOSE", "USER", "LABEL":
					data.MetaInstructions = append(data.MetaInstructions, inst.Raw)
				case "RUN":
					// Skip apt-get update and related commands.
					if !isAptRelated(inst.Raw) {
						data.MetaInstructions = append(data.MetaInstructions, inst.Raw)
					}
				}
			}
		} else if stage.Alias != "" {
			// This is a build stage — preserve it.
			data.HasBuildStage = true
			data.FinalStageNum = 3
			var sb strings.Builder
			fmt.Fprintf(&sb, "FROM %s", stage.BaseImage)
			if stage.Alias != "" {
				fmt.Fprintf(&sb, " AS %s", stage.Alias)
			}
			sb.WriteString("\n")
			for _, inst := range stage.Lines {
				sb.WriteString(inst.Raw)
				sb.WriteString("\n")
			}
			data.BuildStageContent = strings.TrimRight(sb.String(), "\n")
		}
	}

	if data.OriginalBase == "" && len(info.Stages) > 0 {
		data.OriginalBase = info.Stages[0].BaseImage
	}

	funcMap := template.FuncMap{
		"last": func(i int, s []string) bool {
			return i == len(s)-1
		},
	}

	tmpl, err := template.New("dockerfile").Funcs(funcMap).Parse(chiselDockerfileTemplate)
	if err != nil {
		return nil, fmt.Errorf("internal template error: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("cannot generate dockerfile: %w", err)
	}

	return buf.Bytes(), nil
}

// isAptRelated reports whether a RUN instruction is solely apt-get related.
func isAptRelated(raw string) bool {
	lower := strings.ToLower(raw)
	return strings.Contains(lower, "apt-get update") ||
		strings.Contains(lower, "apt-get install") ||
		strings.Contains(lower, "apt install") ||
		strings.Contains(lower, "rm -rf /var/lib/apt")
}
